sudo: required
services:
  - docker

before_install:
  - docker build -t lukefitz1/react-test -f ./client/Dockerfile.dev ./client

  script: 
    - docker run -e CI=true lukefitz1/react-test npm test -- --coverage

after_success:
  - docker build -t lukefitz1/multi-client ./client
  - docker build -t lukefitz1/multi-nginx ./nginx
  - docker build -t lukefitz1/multi-server ./server
  - docker build -t lukefitz1/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push lukefitz1/multi-client
  - docker push lukefitz1/multi-nginx
  - docker push lukefitz1/multi-server
  - docker push lukefitz1/multi-work